# ===================================================================
# Spring Boot configuration.
#
# This configuration is used for unit/integration tests.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: TestApplication
    
    
server:
   port: 8095  

security:
    basic:
        enabled: false


